name: 'ci'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm add -wD @vitest/coverage-v8

      - name: Run unit tests
        run: pnpm run test:unit -- --coverage.enabled --coverage.reporter=lcov

      - name: Upload coverage to Qlty
        if: always()
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info
          incomplete: true

  ssr-sfc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm add -wD @vitest/coverage-v8

      - name: Build SSR
        run: pnpm run build:ssr

      - name: Run SSR tests
        run: pnpm exec vitest run server-renderer --coverage.enabled --coverage.reporter=lcov

      - name: Upload SSR coverage to Qlty
        if: always()
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info
          incomplete: true

      - name: Run compiler-sfc tests
        run: pnpm run test:sfc -- --coverage.enabled --coverage.reporter=lcov

      - name: Upload SFC coverage to Qlty
        if: always()
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info
          incomplete: true

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - name: Run e2e tests
        run: pnpm run test:e2e

      - name: Run transition tests
        run: pnpm run test:transition

  type-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - name: Run srouce type check
        run: pnpm run ts-check

      - name: Run type declaration tests
        run: pnpm run test:types

  coverage-complete:
    runs-on: ubuntu-latest
    if: always()
    needs: [unit-test, ssr-sfc-test]
    steps:
      - uses: actions/checkout@v4

      - name: Coverage complete
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          complete: true
